import MetricsPlugin, { DEFAULT_METRICS_PATH } from './plugin';
import { DEFAULT_METRIC_NAME_REQUESTS, DEFAULT_METRIC_NAME_PACKAGE_DOWNLOADS } from './metrics';

export default MetricsPlugin;
export { DEFAULT_METRICS_PATH, DEFAULT_METRIC_NAME_REQUESTS, DEFAULT_METRIC_NAME_PACKAGE_DOWNLOADS };
